name: UDI devl RDS Materialized Refresh

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: devl-techbd-sql

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .pgpass file
        run: |
          # Write the metadata comment to the .pgpass file
          echo "# { id: \"DEVL_TECHBD_UDI_DS\", description: \"UDI Devl database \", boundary: \"Development\" }" > ~/.pgpass

          # Append the database connection details to the .pgpass file
          echo "${{ secrets.DEVL_TECHBD_UDI_DS_HOST }}:${{ secrets.DEVL_TECHBD_UDI_DS_PORT }}:${{ secrets.DEVL_TECHBD_UDI_DS_NAME }}:${{ secrets.DEVL_TECHBD_UDI_DS_USER }}:${{ secrets.DEVL_TECHBD_UDI_DS_PASSWORD }}" >> ~/.pgpass

          # Set the .pgpass file permissions to 600 (read and write for owner only)
          chmod 600 ~/.pgpass

      - name: Refresh Materialized views
        run: |
          psql -h ${{ secrets.DEVL_TECHBD_UDI_DS_HOST }} \
               -p ${{ secrets.DEVL_TECHBD_UDI_DS_PORT }} \
               -U ${{ secrets.DEVL_TECHBD_UDI_DS_USER }} \
               -d ${{ secrets.DEVL_TECHBD_UDI_DS_NAME }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.interaction_http_request_observe_mat;"
          psql -h ${{ secrets.DEVL_TECHBD_UDI_DS_HOST }} \
               -p ${{ secrets.DEVL_TECHBD_UDI_DS_PORT }} \
               -U ${{ secrets.DEVL_TECHBD_UDI_DS_USER }} \
               -d ${{ secrets.DEVL_TECHBD_UDI_DS_NAME }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.interaction_http_request_resource_type_mat;"
          psql -h ${{ secrets.DEVL_TECHBD_UDI_DS_HOST }} \
               -p ${{ secrets.DEVL_TECHBD_UDI_DS_PORT }} \
               -U ${{ secrets.DEVL_TECHBD_UDI_DS_USER }} \
               -d ${{ secrets.DEVL_TECHBD_UDI_DS_NAME }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.interaction_http_request_mat;"
          psql -h ${{ secrets.DEVL_TECHBD_UDI_DS_HOST }} \
               -p ${{ secrets.DEVL_TECHBD_UDI_DS_PORT }} \
               -U ${{ secrets.DEVL_TECHBD_UDI_DS_USER }} \
               -d ${{ secrets.DEVL_TECHBD_UDI_DS_NAME }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.fhir_screening_info_mat;"
          psql -h ${{ secrets.DEVL_TECHBD_UDI_DS_HOST }} \
               -p ${{ secrets.DEVL_TECHBD_UDI_DS_PORT }} \
               -U ${{ secrets.DEVL_TECHBD_UDI_DS_USER }} \
               -d ${{ secrets.DEVL_TECHBD_UDI_DS_NAME }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.fhir_validation_issue_mat;" 
