name: UDI Prime RDS Materialized Refresh

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: techbd-sql

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .pgpass file
        run: |
          # Write the metadata comment to the .pgpass file
          echo "# { id: \"PROD_TECHBD_UDI_DS_PRIME\", description: \"UDI Prime database \", boundary: \"Production\" }" > ~/.pgpass

          # Append the database connection details to the .pgpass file
          echo "${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PORT }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_NAME }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_USER }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PASSWORD }}" >> ~/.pgpass

          # Set the .pgpass file permissions to 600 (read and write for owner only)
          chmod 600 ~/.pgpass

      - name: Refresh Materialized views
        run: |
          psql -h ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }} \
               -p ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PORT }} \
               -U ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_USER }} \
               -d ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_NAME }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.interaction_http_request_observe_mat;"
          psql -h ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }} \
               -p ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PORT }} \
               -U ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_USER }} \
               -d ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_NAME }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.interaction_http_request_resource_type_mat;"
          psql -h ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }} \
               -p ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PORT }} \
               -U ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_USER }} \
               -d ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_NAME }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.interaction_http_request_mat;"
          psql -h ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }} \
               -p ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PORT }} \
               -U ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_USER }} \
               -d ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_NAME }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.fhir_screening_info_mat;"
          psql -h ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }} \
               -p ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }} \
               -U ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }} \
               -d ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }} \
               -c "REFRESH MATERIALIZED VIEW techbd_udi_ingress.fhir_validation_issue_mat;"
